LEFT_EYE_HORIZONTAL_EXTREMES=[36,39]
LEFT_EYE_TOP=[37,38]
LEFT_EYE_BOTTOM=[41,40]

RIGHT_EYE_HORIZONTAL_EXTREMES=[42,45]
RIGHT_EYE_TOP=[43,44]
RIGHT_EYE_BOTTOM=[47,46]

LEFT_LETTERS=['A','B','C','D','E','F','G','H','I','J','_','K','L','M',"Back"]
RIGHT_LETTERS=['N','O','P','Q','R','S','T','U','V','W',"?",'X','Y','Z',"Back"]

FPS=25